version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[dependabot-gh-actions] "
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
