version: 2
jobs:
  build:
#    working_directory: ~/circleci-demo-java-spring # directory where steps will run
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - restore_cache:
          key: circleci-pdfdebugger-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-pdfdebugger-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/pdftool-2.0-SNAPSHOT.jar
