name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  QA:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Verify
        run: ./mvnw --no-transfer-progress verify

      - name: Upload coverage report
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: target/coverage-reports/jacoco-ut/jacoco.xml

  image-build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build image
        run: ./scripts/containerize.sh
        env:
          CONTAINER_REGISTRY: docker.io
          OUTPUT_MODE: Tar
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          input: target/jib-image.tar
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
