name: Build container image

on:
  create:
    tags: "*"

jobs:
  jib_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build image
        run: ./scripts/containerize.sh
        env:
          CONTAINER_REGISTRY: docker.io
          OUTPUT_MODE: tar

      - name: Run vulnerability scanner
        uses: aquasecurity/trivy-action@0.12.0
        with:
          input: target/jib-image.tar
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
#          severity: "CRITICAL,HIGH"
