name: Docker build

on:
  create:
    tags: "*"

jobs:
  jib_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      # Split push and validate
      - name: Jib
        run: ./mvnw --no-transfer-progress package jib:build -Ddocker.tag=${GITHUB_REF#refs/tags/} -Djib.to.auth.username=${{ secrets.DOCKER_USERNAME }} -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
